; Liliam: Encore mode - palette

PalID2_AIZIntro:	palptr Pal_AIZIntro_Encore,	Normal_palette_line_2,	$60
PalID2_AIZFire:		palptr Pal_AIZFire_Encore,	Normal_palette_line_2,	$60
PalID2_HCZ1:		palptr Pal_HCZ1_Encore,		Normal_palette_line_2,	$60
PalID2_HCZ2:		palptr Pal_HCZ2_Encore,		Normal_palette_line_2,	$60
PalID2_MGZ:		palptr Pal_MGZ_Encore,		Normal_palette_line_2,	$60
PalID2_CNZ:		palptr Pal_CNZ_Encore,		Normal_palette_line_2,	$60
PalID2_FBZ:		palptr Pal_FBZ_Encore,		Normal_palette_line_2,	$60
PalID2_ICZ1:		palptr Pal_ICZ1_Encore,		Normal_palette_line_2,	$60
PalID2_ICZ2:		palptr Pal_ICZ2_Encore,		Normal_palette_line_2,	$60
PalID2_LBZ1:		palptr Pal_LBZ1_Encore,		Normal_palette_line_2,	$60
PalID2_LBZ2:		palptr Pal_LBZ2_Encore,		Normal_palette_line_2,	$60
PalID2_MHZ1:		palptr Pal_MHZ1_Encore,		Normal_palette_line_2,	$60
PalID2_MHZ2:		palptr Pal_MHZ2_Encore,		Normal_palette_line_2,	$60
PalID2_SOZ1:		palptr Pal_SOZ1_Encore,		Normal_palette_line_2,	$60
PalID2_SOZ2:		palptr Pal_SOZ2_Encore,		Normal_palette_line_2,	$60
PalID2_LRZ1:		palptr Pal_LRZ1_Encore,		Normal_palette_line_2,	$60
PalID2_LRZ2:		palptr Pal_LRZ2_Encore,		Normal_palette_line_2,	$60
PalID2_SSZ1:		palptr Pal_SSZ1_Encore,		Normal_palette_line_2,	$60
PalID2_SSZ2:		palptr Pal_SSZ2_Encore,		Normal_palette_line_2,	$60
PalID2_DEZ1:		palptr Pal_DEZ1_Encore,		Normal_palette_line_2,	$60
PalID2_DEZ2:		palptr Pal_DEZ2_Encore,		Normal_palette_line_2,	$60
PalID2_DDZ:		palptr Pal_DDZ_Encore,		Normal_palette_line_2,	$60
PalID2_Ending:		palptr Pal_Ending2,		Normal_palette_line_2,	$60
PalID2_ALZ:		palptr Pal_ALZ,			Normal_palette_line_2,	$60
PalID2_ALZ_2:		palptr Pal_ALZ_Encore,		Normal_palette_line_2,	$60
PalID2_BPZ:		palptr Pal_BPZ,			Normal_palette_line_2,	$60
PalID2_BPZ_2:		palptr Pal_BPZ_Encore,		Normal_palette_line_2,	$60
PalID2_AIZ:		palptr Pal_AIZ_Encore,		Normal_palette_line_2,	$60
PalID2_AIZ_Water:	palptr Pal_AIZ_Water_Encore,	Normal_palette,		$80
PalID2_AIZ2_Water:	palptr Pal_AIZ2_Water_Encore,	Normal_palette,		$80
PalID2_LBZ2_Water:	palptr Pal_LBZ_Water_Encore,	Normal_palette,		$80
PalID2_AIZBoss:		palptr Pal_AIZBoss_Encore,	Normal_palette_line_2,	$60
PalID2_HCZ1_Water:	palptr Pal_HCZ1_Water_Encore,	Normal_palette,		$80
PalID2_HCZ2_Water:	palptr Pal_HCZ2_Water_Encore,	Normal_palette,		$80
PalID2_Gumball:		palptr Pal_Gumball_Special,	Normal_palette_line_2,	$60
PalID2_DPZ:		palptr Pal_DPZ,			Normal_palette_line_2,	$60
PalID2_DPZ_2:		palptr Pal_DPZ_Encore,		Normal_palette_line_2,	$60
PalID2_CGZ:		palptr Pal_CGZ,			Normal_palette_line_2,	$60
PalID2_CGZ_2:		palptr Pal_CGZ_Encore,		Normal_palette_line_2,	$60
PalID2_EMZ:		palptr Pal_EMZ,			Normal_palette_line_2,	$60
PalID2_EMZ_2:		palptr Pal_EMZ_Encore,		Normal_palette_line_2,	$60
PalID2_Pachinko:	palptr Pal_Pachinko_Special,	Normal_palette_line_2,	$60
PalID2_Slots:		palptr Pal_Slot_Special,	Normal_palette_line_2,	$60
PalID2_Slots_2:		palptr Pal_Encore_Special,	Normal_palette,		$80
PalID2_ICZ2_Water:	palptr Pal_ICZ2_Water_Encore,	Normal_palette,		$80
PalID2_CNZ_Water:	palptr Pal_CNZ_Water_Encore,	Normal_palette,		$80
PalID2_LRZBoss:		palptr Pal_LRZBoss_Encore,	Normal_palette_line_2,	$60
PalID2_HPZIntro:	palptr Pal_HPZIntro,		Normal_palette_line_2,	$60
PalID2_DEZBoss:		palptr Pal_DEZBoss_Encore,	Normal_palette_line_2,	$60
PalID2_HPZ:		palptr Pal_HPZIntro,		Normal_palette_line_2,	$60
