; Fred: Encore mode - palette

		dc.l Pal_AIZIntro_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_AIZFire_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_HCZ1_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_HCZ2_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_MGZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_MGZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_CNZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_CNZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_FBZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_FBZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ICZ1_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ICZ2_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_LBZ1_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_LBZ2_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_MHZ1_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_MHZ2_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_SOZ1_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_S0Z2_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_LRZ1_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_LRZ2_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_SSZ1_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_SSZ2_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_DEZ1_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_DEZ2_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_DDZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_DDZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_Encore_Special
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_Ending_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ALZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ALZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_BPZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_BPZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_AIZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_AIZ_Water_Encore
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_AIZ2_Water_Encore
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_LBZ_Water_Encore
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_LBZ_Water_Encore
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_LBZ_Water2_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_AIZBoss_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_HCZ1_Water_Encore
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_HCZ2_Water_Encore
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_Gumball_Special
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_DPZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_CGZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_EMZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_Pachinko_Special
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_Slot_Special
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ICZ2_Water_Encore
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_CNZ_Water_Encore
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_DPZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_CGZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_EMZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_LRZBoss_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_HPZIntro_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_DEZBoss_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_HPZ_Encore
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
